engines:
  markdownlint:
    enabled: true
    checks:
        MD002:
            enabled: false

exclude_paths:
  - css/**/*
  - fonts/**/*
  - js/**/*
  - common_images/**/*
  - _layouts/**/*
  - _includes/**/*
  - _data/**/*

ratings:
  paths:
    - "**.md"
