project: haxe-checkstyle
output: web
destination: doc_outputs/haxe-checkstyle
topnav_title: Haxe Checkstyle Documentation
site_title: Haxe Checkstyle Documentation
homepage_title: Home
url: /docs/
project_folder: haxe-checkstyle
company_name: Haxe Checkstyle
footer_image_location: common_images/icon.png
# variables

sidebar_tagline:
sidebar_version:
theme_file: theme-orange.css

port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/docs*
  - node_modules
  - .temp
  - .idea
  - .n

# same for all
host: 127.0.0.1

highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true